### ISSUE TITLE
Inaccurate book info

### ISSUE THREAD

**Issue by elizabethyalkut** [AnandChowdhary/bookshelf-action#104]
Two separate kinds of inaccuracy:

1. When I add books that are sequels, or in a series, the "congrats on adding" seems to think I want the metadata for the previous book (e.g., I added `A prayer for the crown-shy by Becky Chambers`, and the actions should find https://www.google.com/books/edition/A_Prayer_for_the_Crown_Shy/ipc9EAAAQBAJ?hl=en&gbpv=0 but instead find https://www.google.com/books/edition/_/_Qu_zQEACAAJ?hl=en; adding `The golden enclaves by Naomi Novik` gets me `The last graduate` which is the second in a trilogy, but I'm reading the final book.).
2. Sometimes the info is just ...wrong. `The useful book : 201 life skills they used to teach in home ec and shop by Sharon and David Bowers` ([which does exist in Google Books](https://www.google.com/books/edition/_/rVwbDAAAQBAJ?hl=en&gbpv=0))gets me metadata on [Lois McMaster Bujold's A Civil Campaign](https://books.google.com/books?id=l8HZ7joLk8kC&dq=intitle:+The+useful+book+:+201+life+skills+they+used+to+teach+in+home+ec+and+shop+/+Sharon+and+David+Bowers+%3B+illustrated+by+Sophia+Nicolay.&hl=&source=gbs_api), which is a _novel_, not non-fiction and totally unrelated as far as I can tell.

**Comment by AnandChowdhary** [comment]
Damn, that's not good! :(

As you can see in the following line, we just use the Google Books Search API and use the first available result. Maybe a good test would be for you to try your query using the same API and seeing if the correct result shows up as the second or third link? If that's the case, perhaps we can get Bookshelf Action to write a comment on the issue with options and ask the user to select the book they mean?

https://github.com/AnandChowdhary/bookshelf-action/blob/0012ee48d266606fb0a140179564a81e48a0d5fe/src/google-books.ts#L63

**Comment by elizabethyalkut** [comment]
More than happy to test!

I didn't notice before, but this may be semi-intentional or an error on the part of Google Books? The full JSON received for the Chambers book I mentioned is below
```
Book details (JSON)

{
  "title": "A Psalm for the Wild-Built",
  "authors": [
    "Becky Chambers"
  ],
  "publisher": "Tordotcom",
  "publishedDate": "2021-07-13",
  "description": "Winner of the Hugo Award! In A Psalm for the Wild-Built, bestselling Becky Chambers's delightful new Monk and Robot series, gives us hope for the future. It's been centuries since the robots of Panga gained self-awareness and laid down their tools; centuries since they wandered, en masse, into the wilderness, never to be seen again; centuries since they faded into myth and urban legend. One day, the life of a tea monk is upended by the arrival of a robot, there to honor the old promise of checking in. The robot cannot go back until the question of \"what do people need?\" is answered. But the answer to that question depends on who you ask, and how. They're going to need to ask it a lot. Becky Chambers's new series asks: in a world where people have what they want, does having more matter?",
  "image": "http://books.google.com/books/content?id=_Qu_zQEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
  "language": "en",
  "averageRating": 4,
  "ratingsCount": 37,
  "categories": [
    "Fiction"
  ],
  "pageCount": 0,
  "isbn10": "1250236215",
  "isbn13": "9781250236210",
  "googleBooks": {
    "id": "_Qu_zQEACAAJ",
    "preview": "http://books.google.com/books?id=_Qu_zQEACAAJ&dq=intitle:A+prayer+for+the+crown-shy+by+Becky+Chambers&hl=&cd=3&source=gbs_api",
    "info": "http://books.google.com/books?id=_Qu_zQEACAAJ&dq=intitle:A+prayer+for+the+crown-shy+by+Becky+Chambers&hl=&source=gbs_api",
    "canonical": "https://books.google.com/books/about/A_Psalm_for_the_Wild_Built.html?hl=&id=_Qu_zQEACAAJ"
  }
}
```
I draw your attention specifically to the "info" and "canonical" data. ?????

Anyway!

`https://www.googleapis.com/books/v1/volumes?q=intitle:${A+prayer+for+the+crown-shy+by+Becky+Chambers}` does in fact get me three items, [0] and [1] are the correct book (possibly a print vs. ebook thing?) and [2] is the first book in the series, so yeah, manually-confirming which of multiple items retrieved is correct would seem to work.

On the other hand:
`https://www.googleapis.com/books/v1/volumes?q=intitle:${The%20useful%20book%20:%20201%20life%20skills%20they%20used%20to%20teach%20in%20home%20ec%20and%20shop}` gets me _five_ items, two of which are the book I want and three of which are ...a low-res scan from the New York Times Book Review, a low-res scan from The Publishers' Trade List Annual, and (🥁 🥁 ) The Compact Edition of the Oxford English Dictionary: Complete Text Reproduced Micrographically: P-Z, Supplement and bibliography. It's not even _the same wrong book_. I have literally no idea what's going on. Presumably the same manual confirmation process would work, since it does retrieve correct information along with the nonsense, but 🤯 !

**Comment by AnandChowdhary** [comment]
Aah I understand, thanks for the test! You're right, the manual confirmation process would fix this issue as well, and we should give people options!

I'll work on this as soon as I have some time on my hands, perhaps over the weekend, but if anyone wants to pick up the PR, I'm more than happy to review and merge!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
