### ISSUE TITLE
Resource not accessible by integration when creating new issue / adding book

### ISSUE THREAD

**Issue by hammygoonan** [AnandChowdhary/bookshelf-action#107]
Hi there, I'm getting an error when creating a new issue saying `Resource not accessible by integration`.

Is there a step I'm missing or something?

You can see the failed action here: https://github.com/hammygoonan/books/actions/runs/3889210955/jobs/6637283083

**Comment by AnandChowdhary** [comment]
It looks like this is because the token doesn't have permission to create a comment. Could it be that the default permission of your token is readonly? https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token

**Comment by hammygoonan** [comment]
I had some success changing Workflow permissions to "Read and write permissions". The actions were still failing but getting far enough through to update the README.md file.

You can see an example [here](https://github.com/hammygoonan/books/actions/runs/3892115228/jobs/6643155310).

**Comment by AnandChowdhary** [comment]
Perfect. Can you please delete the lines starting and including `- name: Dispatch AnandChowdhary/everything update` in all the workflows? You don't need those.

**Comment by hammygoonan** [comment]
That looks like it's got it. Thanks!

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by Zaid-maker** [comment]
Hi There! i am getting the same error

**Comment by AnandChowdhary** [comment]
Can you please show me your repository?

**Comment by Zaid-maker** [comment]
> Can you please show me your repository?

Ok lwt me explain!

i create the repo using "Use this template" and i saw the Initial Action run and passed but no error given but it says Permission denied to github-actions bot so i manually give permissions and re ran the workdlow and it runs and changes files [Check the commit here](https://github.com/Zaid-maker/books/commit/7505ca59bee3582f05fce3a9032b143ae8eb5023)

**Comment by AnandChowdhary** [comment]
This should be fixed now if you create a template repository again. I added the condition that ensures that `AnandChowdhary/everything` is only updated if it's my repository in https://github.com/AnandChowdhary/books/blob/e979de6ab8ca8dcc94c244371d943e56571d9e14/.github/workflows/bookshelf-new-issue.yml#L25
