### ISSUE TITLE
Minor formatting issue

### ISSUE THREAD

**Issue by hammygoonan** [AnandChowdhary/bookshelf-action#108]
When I add a new book with the "want to read" label I'm seeing a small formatting issue. The `### ⏭️ Want to Read (5)` header is appearing on the same line as "Currently reading" if there's no "Complete" books.

At least I assume that's the issue.

<img width="737" alt="Screenshot 2023-01-11 at 10 43 12 pm" src="https://user-images.githubusercontent.com/476520/211797921-498f76e1-a88c-4cfb-857b-45f838c4b9cb.png">

**Comment by AnandChowdhary** [comment]
Yes, this is indeed very weird. Can you please share a link to your repository and I'll look at the raw README?

**Comment by hammygoonan** [comment]
Of course: https://github.com/hammygoonan/books/

I've added some completed books now though so it's all working. However that does confirm my suspicion that the issue is when you have books in 'reading' and 'want to read' but nothing in 'complete'.

**Comment by AnandChowdhary** [comment]
You're right, that could totally be the case. I'll have a look!
