### ISSUE TITLE
Paginate issues and comments

### ISSUE THREAD

**Issue by AnandChowdhary** [AnandChowdhary/bookshelf-action#118]
In https://github.com/AnandChowdhary/bookshelf-action/blob/1057bcc41d2628365f96b1d1896bee3110cc6690/src/features/update-summary.ts#LL24C3-L24C3, we should paginate since we only see a subset of issues currently.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by AnandChowdhary** [comment]
You're right, we can increase the up to 100 but I still think it's best to have it paginated and then we can show all of them, even if they're more than 100.
