### ISSUE TITLE
Parameter ''using: node18' is not supported

### ISSUE THREAD

**Issue by soker90** [AnandChowdhary/bookshelf-action#124]
Hi!

I started getting an error when commenting issues:

> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter ''using: node18' is not supported, use 'docker', 'node12', 'node16' or 'node20' instead.')

You can see it here https://github.com/soker90/libros/actions/runs/6565329654

I resolved this by downgrading the action to v1.1.0

Thank you!

**Comment by Zaid-maker** [comment]
@soker90 I am really sorry for the mistake but I correct it and open a pr #123

**Comment by AnandChowdhary** [comment]
This should be all fixed now! :)
