### ISSUE TITLE
Ability to add notes as comments

### ISSUE THREAD

**Issue by bjork24** [AnandChowdhary/bookshelf-action#95]
First, thank you for creating this project! It's very creative and useful. I have an idea for an additional feature. I like to write a sentence or two summarizing each chapter as I finish them, and I'm sure others would find it useful to leave notes or summaries as well. Could you add the ability to leave a note as an issue comment? Perhaps it would make sense to prepend `Note:` so the github action knows how to process it. Thanks!

**Comment by AnandChowdhary** [comment]
I think this is an amazing idea. I love taking notes and I end up ruining my books by highlighting and underlining things (though I use pencils, I swear!) so using GitHub comments for notes sounds like the perfect solution. I'll work on this!

**Comment by AnandChowdhary** [comment]
Currently, if you have a number in the notes, the Action tries to parse it to figure out the page number, e.g., "I'm on page 200" will mark a 500-page book as 40% completed. So you're right, you can already just comment on the issues as long as they don't have a number in them. But of course, we can have a rule, like the `Note:` prefix, that would ignore numbers.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
