### ISSUE TITLE
Add a "Like to read" section

### ISSUE THREAD

**Issue by ciwchris** [AnandChowdhary/bookshelf-action#96]
I maintain a list of books I'd like to read. It would handy if I could maintain this list here too, alongside the "Currently read" and "Completed" lists.

**Comment by AnandChowdhary** [comment]
Currently, we use the issue state open/closed to determine if a book is completed or currently reading. Perhaps we can use a label "reading" and "want to read" to distinguish open issues?

**Comment by AnandChowdhary** [comment]
A basic version has been added where if you label an issue "want to read", the book will be added to a separate "Want to read" list instead of "Reading". :)
